##                                                              SciPy 

SciPy is a collection of mathematical algorithms and convenience functions built on the Numpy extension of Python. It adds significant power to the interactive Python session by providing the user with high-level commands and classes for manipulating and visualizing data. With SciPy an interactive Python session becomes a data-processing and system-prototyping environment rivaling systems such as MATLAB, IDL, Octave, R-Lab, and SciLab

In [2]:
import numpy as np 

A = np.array([[1,2,3,4],[4,5,6,1],[7,8,8,3],[5,3,2,7]])
B = np.arange(16).reshape(4,4)

### Linear Algebra operations


In [2]:
from scipy import linalg

# Compute the determinant of a matrix (note: the matrix should a square matrix)
linalg.det(A)

81.00000000000004

In [3]:
#compute inverse of a matrix
linalg.inv(A)

# matrix inverse cannot be computed on a singular matrix

array([[-0.49382716,  0.90123457, -0.59259259,  0.40740741],
       [ 0.37037037, -1.92592593,  1.44444444, -0.55555556],
       [-0.01234568,  1.19753086, -0.81481481,  0.18518519],
       [ 0.19753086, -0.16049383,  0.03703704,  0.03703704]])

In [4]:
B= np.arange(16).reshape(4,4)

### Creating a sparce matrix

In [8]:
from scipy import sparse

# Create a random array with a lot of zeros
rnd = np.random.randint(0,1)
X[X < 0.8] = 0
print(X)

# turn X into a CSR (Compressed-Sparse-Row) matrix
X_csr = sparse.csr_matrix(X)
print(X_csr)

[[0.         0.         0.         0.         0.        ]
 [0.         0.9807642  0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.84943179 0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.89338916 0.94416002 0.        ]
 [0.         0.         0.         0.         0.86630916]
 [0.         0.         0.98555979 0.         0.        ]]
  (1, 1)	0.9807641983846155
  (4, 1)	0.8494317940777896
  (7, 2)	0.8933891631171348
  (7, 3)	0.9441600182038796
  (8, 4)	0.8663091578833659
  (9, 2)	0.985559785610705


### Compute pivoted SVD decomposition of a matrix.

The decomposition is::
A = SVD


where P is a permutation matrix, L lower triangular with unit diagonal elements, and U upper triangular.


In [52]:
SVD = np.random.randint(10, size=(1, 12)).reshape(3,4)
u_arr, s_arr, v_arr = linalg.svd(SVD)

In [53]:
print('U matrix: ', u_arr, '\n',#Unitary matrix having left singular vectors as columns. Of shape (M, M) or (M, K)
     '\n','S matrix: ', s_arr, '\n',#The singular values, sorted in non-increasing order. Of shape (K,)
     '\n','V matrix: ', v_arr) #Unitary matrix having right singular vectors as rows. Of shape (N, N) or (K, N)

U matrix:  [[-0.42967742  0.66243808 -0.61363923]
 [-0.87627825 -0.46993963  0.10626939]
 [-0.2179765   0.58338027  0.78240252]] 
 
 S matrix:  [14.45721548  4.47864863  2.63260843] 
 
 V matrix:  [[-0.57405648 -0.39382566 -0.55824262 -0.45135981]
 [-0.39570033 -0.36905713 -0.01260308  0.84086815]
 [-0.37634254  0.83659286 -0.35260415  0.18479448]
 [-0.61012023  0.09386465  0.75091721 -0.23466163]]
